language: python
python:
- "2.7"
# command to install  dependencies
install:
- pip install pytest pytest-cov
- pip install mockito
- pip install pep8
- pip install radon
- pip install coveralls
- pip install radon
# command to run tests
script:
- py.test --cov . --cov-report term-missing
after_success:
- coveralls
- radon cc -a src/
- radon cc -a tests/
- radon raw src/
- radon raw tests/
- radon mi src/
- radon mi tests/
- pep8 --statistics --count src/
- pep8 --statistics --count tests/
notifications:
  email:
    recipients:
      - davidsilva4666@gmail.com